# Generated by Django 6.0.6 on 2026-07-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='', max_length=255)),
                ('currency', models.CharField(default='PHP', max_length=10)),
                ('date_format', models.CharField(default='MM/DD/YYYY', max_length=20)),
                ('timezone', models.CharField(default='Asia/Manila', max_length=50)),
                ('language', models.CharField(default='en-PH', max_length=50)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=12, max_digits=5)),
                ('business_name', models.CharField(blank=True, max_length=255)),
                ('business_address', models.TextField(blank=True)),
                ('business_contact', models.CharField(blank=True, max_length=15)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('tin', models.CharField(blank=True, max_length=50)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
            },
        ),
    ]
