# Generated by Django 6.0.6 on 2026-07-21 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('systemsetting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_alerts', models.BooleanField(default=True)),
                ('near_expiry_alerts', models.BooleanField(default=True)),
                ('new_order_alerts', models.BooleanField(default=True)),
                ('forecast_warnings', models.BooleanField(default=True)),
                ('report_ready_notifications', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Settings',
            },
        ),
    ]
