# Generated by Django 6.0.6 on 2026-07-14 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='deactivation_reason',
            field=models.CharField(choices=[('none', 'N/A'), ('leave', 'On Leave'), ('suspended', 'Suspended'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='none', max_length=20),
        ),
    ]
