# Generated by Django 6.0.6 on 2026-07-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_deactivation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='users',
            name='last_password_change_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='last_profile_update_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
