# Generated by Django 6.0.6 on 2026-07-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fefoconf',
            name='critical_expiry_threshold',
            field=models.IntegerField(default=3),
        ),
    ]
