# Generated by Django 6.1 on 2026-08-27 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ingredient_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientbatch',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productbatch',
            name='batch_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
