# Generated by Django 6.0.6 on 2026-07-05 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockadjustment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FEFOConf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('near_expiry_threshold', models.IntegerField(default=7)),
                ('global_low_stock_threshold', models.IntegerField(default=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FEFO Configuration',
            },
        ),
    ]
