# Generated by Django 6.0.6 on 2026-07-05 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_fefoconf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fefoconf',
            old_name='global_low_stock_threshold',
            new_name='low_stock_threshold',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_type',
            field=models.CharField(choices=[('raw_milk', 'Raw Milk'), ('processing', 'Processing'), ('packaging', 'Packaging')], default='raw_milk', max_length=20),
        ),
    ]
