# Generated by Django 6.1 on 2026-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbatch',
            name='is_historical_reference',
            field=models.BooleanField(default=False),
        ),
    ]
