# Generated by Django 6.1 on 2026-10-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_productbatch_is_historical_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, choices=[('milk', 'Milk'), ('cheese', 'Cheese'), ('butter', 'Butter'), ('yogurt', 'Yogurt'), ('ice_cream', 'Ice Cream'), ('cream', 'Cream'), ('package', 'Package')], default='', max_length=20),
        ),
    ]
