"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

DJANGO_ENV = os.getenv('DJANGO_ENV', 'development').strip().lower()
IS_PRODUCTION = DJANGO_ENV == 'production'
DEBUG = env_bool('DJANGO_DEBUG', not IS_PRODUCTION)
if IS_PRODUCTION and DEBUG:
    raise ImproperlyConfigured('DJANGO_DEBUG must be false in production.')

SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', '')
if not SECRET_KEY:
    if IS_PRODUCTION:
        raise ImproperlyConfigured('DJANGO_SECRET_KEY is required in production.')
    SECRET_KEY = 'django-insecure-development-only-change-before-production'

ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,[::1]' if not IS_PRODUCTION else ''
)
if IS_PRODUCTION and not ALLOWED_HOSTS:
    raise ImproperlyConfigured('DJANGO_ALLOWED_HOSTS is required in production.')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'inventory',
    'accounts',
    'sales',
    'systemsetting',
    'reporting',
    'forecasting',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'systemsetting.middleware.RuntimeSettingsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
#   Postgre
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'rosario_dairy'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'root' if not IS_PRODUCTION else ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }

}
if IS_PRODUCTION and not DATABASES['default']['PASSWORD']:
    raise ImproperlyConfigured('DB_PASSWORD is required in production.')

REDIS_URL = os.getenv('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.redis.RedisCache',
            'LOCATION': REDIS_URL,
        }
    }
elif IS_PRODUCTION:
    raise ImproperlyConfigured('REDIS_URL is required in production.')
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'rosario-dairy-development',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = os.getenv('DJANGO_TIME_ZONE', 'Asia/Manila')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/minute',
        'password_reset_request': '5/minute',
        'password_reset_confirm': '10/minute',
    },
}
if os.getenv('DJANGO_NUM_PROXIES'):
    REST_FRAMEWORK['NUM_PROXIES'] = int(os.environ['DJANGO_NUM_PROXIES'])

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'UPDATE_LAST_LOGIN': True,
    'CHECK_REVOKE_TOKEN': True,
}

AUTH_USER_MODEL = 'accounts.Users'

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'http://localhost:5173,https://localhost' if not IS_PRODUCTION else '',
)

CORS_ALLOWED_ORIGIN_REGEXES = [
    r'^https://[a-z0-9]+-5173\.asse\.devtunnels\.ms$',
] if not IS_PRODUCTION else []

CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', IS_PRODUCTION)
SESSION_COOKIE_SECURE = env_bool('DJANGO_SESSION_COOKIE_SECURE', IS_PRODUCTION)
CSRF_COOKIE_SECURE = env_bool('DJANGO_CSRF_COOKIE_SECURE', IS_PRODUCTION)
SECURE_HSTS_SECONDS = int(
    os.getenv('DJANGO_SECURE_HSTS_SECONDS', '3600' if IS_PRODUCTION else '0')
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(
    'DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS', False
)
SECURE_HSTS_PRELOAD = env_bool('DJANGO_SECURE_HSTS_PRELOAD', False)
if env_bool('DJANGO_BEHIND_HTTPS_PROXY', IS_PRODUCTION):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Django sends OTP messages through any configured SMTP provider. Development
# keeps the console backend until a complete SMTP configuration is supplied.
SMTP_HOST = os.getenv('SMTP_HOST', '').strip()
SMTP_USER = os.getenv('SMTP_USER', '').strip()
SMTP_PASSWORD = os.getenv('SMTP_PASSWORD', '')
smtp_values = (SMTP_HOST, SMTP_USER, SMTP_PASSWORD)
if any(smtp_values) and not all(smtp_values):
    raise ImproperlyConfigured('SMTP_HOST, SMTP_USER, and SMTP_PASSWORD must be set together.')

EMAIL_HOST = SMTP_HOST
EMAIL_HOST_USER = SMTP_USER
EMAIL_HOST_PASSWORD = SMTP_PASSWORD

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
elif IS_PRODUCTION:
    raise ImproperlyConfigured('SMTP_HOST, SMTP_USER, and SMTP_PASSWORD are required in production.')
else:
    EMAIL_BACKEND = os.getenv('DJANGO_EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

try:
    EMAIL_PORT = int(os.getenv('SMTP_PORT', '587'))
except ValueError as exc:
    raise ImproperlyConfigured('SMTP_PORT must be a number.') from exc
EMAIL_USE_TLS = env_bool('SMTP_USE_TLS', True)
EMAIL_USE_SSL = env_bool('SMTP_USE_SSL', False)
if EMAIL_USE_TLS and EMAIL_USE_SSL:
    raise ImproperlyConfigured('Use either SMTP_USE_TLS or SMTP_USE_SSL, not both.')
EMAIL_TIMEOUT = 10
DEFAULT_FROM_EMAIL = os.getenv(
    'DEFAULT_FROM_EMAIL', '' if IS_PRODUCTION or EMAIL_HOST else 'Rosario Dairy <noreply@localhost>'
)
if (IS_PRODUCTION or EMAIL_HOST) and not DEFAULT_FROM_EMAIL:
    raise ImproperlyConfigured('DEFAULT_FROM_EMAIL is required when SMTP is configured.')

PASSWORD_RESET_OTP_TIMEOUT = 10 * 60
PASSWORD_RESET_OTP_RESEND_COOLDOWN = 60
PASSWORD_RESET_OTP_MAX_ATTEMPTS = 5
