# Generated by Django 6.1 on 2026-08-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='fulfilled', max_length=20),
        ),
    ]
