# Generated by Django 6.0.6 on 2026-07-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_voided',
            field=models.BooleanField(default=False),
        ),
    ]
