# Generated by Django 6.0.6 on 2026-07-12 15:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_transaction_is_voided'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='amount_tendered',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='change_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
