# Generated by Django 6.0.6 on 2026-07-15 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_transaction_amount_tendered_transaction_change_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionitem',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.transaction'),
        ),
    ]
