# Generated by Django 6.0.6 on 2026-07-17 11:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_transactionitem_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_type',
            field=models.CharField(choices=[('none', 'None'), ('percent', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
