# Generated by Django 6.1 on 2026-10-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customer_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='source_customer_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_invoice_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source_reference',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='source_line_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='transactionitem',
            name='source_product_label',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
