# Generated by Django 6.1 on 2026-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_transaction_source_customer_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('online', 'Online'), ('unknown', 'Not recorded')], default='cash', max_length=20),
        ),
    ]
