# Generated by Django 6.1 on 2026-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('configuration_signature', models.CharField(max_length=64)),
                ('source_signature', models.CharField(max_length=64)),
                ('data_end', models.DateField()),
                ('result', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='IssuedForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=80)),
                ('version', models.CharField(max_length=40)),
                ('configuration_signature', models.CharField(max_length=64)),
                ('setup', models.CharField(max_length=40)),
                ('period', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('trained_through', models.DateField()),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'version', 'configuration_signature', 'setup', 'period', 'date'), name='hybrid_issue_unique'), models.CheckConstraint(condition=models.Q(('trained_through__lt', models.F('date'))), name='hybrid_issue_past_only')],
            },
        ),
    ]
